services:
  clickhouse-mcp:
    image: origin-hub-ai-registry.cn-shanghai.cr.aliyuncs.com/component/mcp-sqlvectordb:0.0.1
    ports:
      - "4200:4200"
    environment:
      - MYSCALE_HOST=127.0.0.1
      - MYSCALE_USER=default
      - MYSCALE_PASSWORD=
      - MYSCALE_PORT=8123
      - MYSCALE_SECURE=false
      - MYSCALE_VERIFY=false
      - MYSCALE_DATABASE=default
      - MCP_SERVER_TRANSPORT=http
      - MCP_BIND_HOST=0.0.0.0
      - MCP_BIND_PORT=4200